The device being used is: cuda

Changed the code!!!!!!!!!!
[34m[1mwandb[0m: [33mWARNING[0m Calling wandb.login() after wandb.init() has no effect.
[34m[1mwandb[0m:   74 of 74 files downloaded. 
[34m[1mwandb[0m:   1 of 1 files downloaded.
/home/danfossautonomypc/segmentation/wandb_segment/src/eval.py:45: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(model_dir))
Traceback (most recent call last):
  File "/home/danfossautonomypc/segmentation/wandb_segment/test.py", line 63, in <module>
    imgs, masks, pred = Test_eval(model, testloader, criterion, device,id2code,model_dir)
  File "/home/danfossautonomypc/segmentation/wandb_segment/src/eval.py", line 45, in Test_eval
    model.load_state_dict(torch.load(model_dir))
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/torch/serialization.py", line 1065, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/torch/serialization.py", line 468, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/torch/serialization.py", line 449, in __init__
    super().__init__(open(name, mode))
IsADirectoryError: [Errno 21] Is a directory: '/home/danfossautonomypc/segmentation/wandb_segment/artifacts/8s.pt:v1'
Traceback (most recent call last):
  File "/home/danfossautonomypc/segmentation/wandb_segment/test.py", line 63, in <module>
    imgs, masks, pred = Test_eval(model, testloader, criterion, device,id2code,model_dir)
  File "/home/danfossautonomypc/segmentation/wandb_segment/src/eval.py", line 45, in Test_eval
    model.load_state_dict(torch.load(model_dir))
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/torch/serialization.py", line 1065, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/torch/serialization.py", line 468, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/torch/serialization.py", line 449, in __init__
    super().__init__(open(name, mode))
IsADirectoryError: [Errno 21] Is a directory: '/home/danfossautonomypc/segmentation/wandb_segment/artifacts/8s.pt:v1'
